export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const SEARCH_PRODUCTS_BY_CATEGORY = 'SEARCH_PRODUCTS_BY_CATEGORY';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
export const SET_LOADING = 'SET_LOADING';